[package]
name = "anylang"
version = "0.1.5"
edition = "2024"


[dependencies]
tauri = { version = "2.11.5", features = ["protocol-asset"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
tokio = { version = "1.53.1", features = ["full"] }
reqwest = { version = "0.13.4", features = ["json"] }
specta = { version = "2.0.0-rc.25", features = ["derive"] }
tauri-specta = { version = "2.0.0-rc.25", features = ["derive", "typescript"] }
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
image = { version = "0.25.10", default-features = false, features = [
    "png",
    "jpeg",
    "webp",
    "bmp",
    "gif",
    "tga",
    "tiff",
    "dds",
] }
xxhash-rust = { version = "0.8.18", features = ["xxh3"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing = { version = "0.1.44", features = ["release_max_level_off"] }
chrono = { version = "0.4.45", default-features = false, features = ["now"] }
jpeg-decoder = { version = "0.3.2", default-features = false }
libwebp-sys = "0.14.4"
walkdir = "2.5.0"
flate2 = "1.1.9"
regex = "1.13.1"
anyhow = "1.0.104"
futures = "0.3.34"
gcp_auth = "0.12.7"
specta-typescript = "0.0.12"
tauri-plugin-dialog = "2.7.2"
include_dir = "0.7.4"
dirs = "6.0.0"
dunce = "1.0.5"
crc32fast = "1.5.1"
lz4 = "1.28.1"
base64 = "0.23.1"
tauri-plugin-opener = "2.5.4"
chacha20 = "0.10.1"
encoding_rs = "0.8.35"
texture2ddecoder = "0.1.2"
lzma-rs = "0.3.0"
imagesize = "0.15.0"


[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }


[dev-dependencies]
tempfile = "3.27.0"


[profile.release]
codegen-units = 1
lto = true
strip = true


[profile.dev.package.xxhash-rust]
opt-level = 3
