// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	pickGame: (dropped: string) => typedError<Opened, string>(__TAURI_INVOKE("pick_game", { dropped })),
	fontShown: (at: string) => typedError<null, string>(__TAURI_INVOKE("font_shown", { at })),
	pictures: (gameDir: string) => typedError<Shot[], string>(__TAURI_INVOKE("pictures", { gameDir })),
	pictureShown: (gameDir: string, key: string, most: number) => typedError<Shown, string>(__TAURI_INVOKE("picture_shown", { gameDir, key, most })),
	savePicture: (gameDir: string, key: string, at: string) => typedError<null, string>(__TAURI_INVOKE("save_picture", { gameDir, key, at })),
	copyPicture: (gameDir: string, key: string) => typedError<null, string>(__TAURI_INVOKE("copy_picture", { gameDir, key })),
	keepPicture: (gameDir: string, at: string) => typedError<string, string>(__TAURI_INVOKE("keep_picture", { gameDir, at })),
	pastePicture: (gameDir: string) => typedError<string | null, string>(__TAURI_INVOKE("paste_picture", { gameDir })),
	replacementShown: (at: string) => typedError<Replacement, string>(__TAURI_INVOKE("replacement_shown", { at })),
	pictureKinds: () => __TAURI_INVOKE<string[]>("picture_kinds"),
	picturesAtOnce: () => __TAURI_INVOKE<number>("pictures_at_once"),
	saveProject: (gameDir: string, project: Project) => typedError<null, string>(__TAURI_INVOKE("save_project", { gameDir, project })),
	previewPrompt: (gameDir: string, project: Project) => typedError<string, string>(__TAURI_INVOKE("preview_prompt", { gameDir, project })),
	survey: (gameDir: string) => typedError<Tally, string>(__TAURI_INVOKE("survey", { gameDir })),
	prepareGame: (gameDir: string, project: Project, afresh: boolean) => typedError<Ready, string>(__TAURI_INVOKE("prepare_game", { gameDir, project, afresh })),
	translateScope: (gameDir: string, scopes: string[]) => typedError<null, string>(__TAURI_INVOKE("translate_scope", { gameDir, scopes })),
	translateLine: (gameDir: string, file: string, id: number) => typedError<string, string>(__TAURI_INVOKE("translate_line", { gameDir, file, id })),
	live: () => typedError<Live, string>(__TAURI_INVOKE("live")),
	stopScope: (scopes: string[]) => typedError<null, string>(__TAURI_INVOKE("stop_scope", { scopes })),
	stopLine: () => __TAURI_INVOKE<void>("stop_line"),
	exportScope: (gameDir: string, scopes: string[]) => typedError<Exported, string>(__TAURI_INVOKE("export_scope", { gameDir, scopes })),
	forgetLogs: (gameDir: string) => typedError<null, string>(__TAURI_INVOKE("forget_logs", { gameDir })),
	clearScope: (gameDir: string, scopes: string[]) => typedError<string[], string>(__TAURI_INVOKE("clear_scope", { gameDir, scopes })),
	revertScope: (gameDir: string, scopes: string[]) => typedError<Exported, string>(__TAURI_INVOKE("revert_scope", { gameDir, scopes })),
	closeProject: () => __TAURI_INVOKE<void>("close_project"),
	deleteProject: (gameDir: string) => typedError<null, string>(__TAURI_INVOKE("delete_project", { gameDir })),
	listRows: (gameDir: string) => typedError<Outline, string>(__TAURI_INVOKE("list_rows", { gameDir })),
	search: (gameDir: string, query: string, how: Seeking) => typedError<Found[] | null, string>(__TAURI_INVOKE("search", { gameDir, query, how })),
	excludeScope: (gameDir: string, scopes: string[], excluded: boolean) => typedError<string[], string>(__TAURI_INVOKE("exclude_scope", { gameDir, scopes, excluded })),
	readLines: (gameDir: string, scope: string, sift: Sift, from: number, count: number) => typedError<Window, string>(__TAURI_INVOKE("read_lines", { gameDir, scope, sift, from, count })),
	readLinesAround: (gameDir: string, scope: string, sift: Sift, file: string, id: number, count: number) => typedError<Window, string>(__TAURI_INVOKE("read_lines_around", { gameDir, scope, sift, file, id, count })),
	saveEntry: (gameDir: string, file: string, id: number, translation: string | null) => typedError<null, string>(__TAURI_INVOKE("save_entry", { gameDir, file, id, translation })),
	loadSettings: () => typedError<Settings, string>(__TAURI_INVOKE("load_settings")),
	saveSettings: (settings: Settings) => typedError<null, string>(__TAURI_INVOKE("save_settings", { settings })),
};

/** Events */
export const events = {
	batchDone: makeEvent<BatchDone>("batch-done"),
	fileDone: makeEvent<FileDone>("file-done"),
	fileStarted: makeEvent<FileStarted>("file-started"),
	notice: makeEvent<Notice>("notice"),
	preparing: makeEvent<Preparing>("preparing"),
	runState: makeEvent<RunState>("run-state"),
};

/* Types */
export type Account = {
	credentials: string,
	model: string,
	temperature?: Temperature,
};

export type BatchDone = {
	file: string,
	filled: number,
	added: number,
};

export type Counts = {
	total: number,
	translated: number,
	untranslated: number,
};

export type Endpoint = {
	baseUrl: string,
	apiKey: string,
	model: string,
	temperature?: Temperature,
};

export type Entry = {
	file: string,
	name: string,
	id: number,
	source: string,
	translation: string | null,
	offer: Offer,
};

export type Era = "any" | "ancient" | "medieval" | "earlyModern" | "victorian" | "earlyTwentieth" | "lateTwentieth" | "modern" | "nearFuture" | "farFuture";

export type Exported = {
	files: number,
	lines: number,
	reverted: number,
	landed: string[],
	gone: string[],
};

export type Fidelity = "literal" | "balanced" | "free";

export type FileDone = {
	file: string,
};

export type FileStarted = {
	file: string,
};

export type Font = {
	name: string,
	at: string,
	shown: string,
	builtin: boolean,
};

export type Fonts = {
	swaps?: Swap[],
};

export type Found = {
	key: string,
	lines: number[],
};

export type Keyed = {
	apiKey: string,
	model: string,
};

export type Level = "info" | "warn" | "error";

export type Live = {
	running: boolean,
	files: string[],
	opened: Opened | null,
	failed: string | null,
};

export type LogEntry = {
	at: string,
	source: Source,
	message: string,
	level: Level,
};

export type Mood = "comic" | "cute" | "dark" | "deadpan" | "dramatic" | "epic" | "explicit" | "melancholic" | "playful" | "sarcastic" | "tense" | "unsettling" | "warm" | "witty";

export type Notice = {
	at: string,
	source: Source,
	message: string,
	level: Level,
};

export type Offer = "asked" | "listed" | "locked";

export type Only = "yours" | "asked" | "listed";

export type Opened = {
	gameDir: string,
	project: Project,
	fresh: boolean,
	piles: boolean,
	sources: string[],
	faces: Font[],
	logs: LogEntry[],
	survey: Tally | null,
};

export type Options = {
	shipped?: string,
};

export type Outline = {
	rows: Row[],
	chosen: Tally,
	whole: Tally,
};

export type Picks = {
	on?: string[],
	off?: string[],
};

export type Pictures = {
	swaps?: Swap[],
	marked?: string[],
};

export type Preparing = {
	steps: string[],
	at: number,
};

export type Project = {
	sourceLanguage: string,
	language: string,
	style: Style,
	fonts?: Fonts,
	tweaks?: Tweaks,
	picks?: Picks,
	pictures?: Pictures,
};

export type Provider = "gemini" | "vertex" | "claude" | "compatible";

export type Ready = {
	survey: Tally,
	faces: Font[],
};

export type Register = "any" | "coarse" | "casual" | "formal" | "elevated";

export type Replacement = {
	body: string,
	mime: string,
	wide: number,
	high: number,
};

export type Row = {
	scope: string,
	label: string,
	kind: string,
	excluded: boolean,
	tally: Tally,
};

export type RunState = {
	running: boolean,
};

export type Sampled = {
	apiKey: string,
	model: string,
	temperature?: Temperature,
};

export type Seeking = {
	cased: boolean,
	whole: boolean,
	regex: boolean,
};

export type Settings = {
	using: Provider,
	gemini: Sampled,
	vertex: Account,
	claude: Keyed,
	compatible: Endpoint,
	linesPerRequest: number,
	parallelRequests: number,
};

export type Shot = {
	key: string,
	holder: string,
	name: string,
	kind: string,
	atlas: string,
	wide: number,
	high: number,
	format: string,
	savedAs: string,
	locked: string | null,
	drawable: boolean,
	at?: string,
};

export type Show = "all" | "translated" | "untranslated";

export type Shown = {
	body: string,
	mime: string,
};

export type Sift = {
	show: Show,
	only: Only,
	needle: string,
	how: Seeking,
};

export type Source = "session" | "project" | "prepare" | "translate" | "export" | "restore" | "clear" | "exclude";

export type Style = {
	fidelity?: Fidelity,
	era?: Era,
	register?: Register,
	genres: string[],
	voices: string[],
	notes: string,
};

export type Swap = {
	from: string,
	to: string,
};

export type Tally = {
	files: number,
	applied: number,
	translated: number,
	total: number,
};

export type Temperature = number | null;

export type Tweaks = { kind: "none" } | {
	kind: "renpy",
} & Options;

export type Window = {
	from: number,
	kept: number,
	counts: Counts,
	lines: Entry[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

